services:
  postgres:
    image: postgres:16-alpine
    container_name: reddit_scraper_db
    environment:
      POSTGRES_USER: reddit_scraper
      POSTGRES_PASSWORD: reddit_scraper_password
      POSTGRES_DB: reddit_scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reddit_scraper"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 