version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: reddit_scraper
      POSTGRES_PASSWORD: reddit_scraper_password
      POSTGRES_DB: reddit_scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 